### ISSUE TITLE
Changing Namespace Prefix?

### ISSUE THREAD

**Issue by steveroger** [rohe/pysaml2#184]
All the SAML requests/responses that I am able to generate are formatted with a namespace prefix of "ns0", or "ns1". The IdP that I am using requires the namespace prefix to be 'saml2p' or 'samlp' instead.

For example, here is an AuthnRequest that I generate using the pysaml2 library:
```
<ns0:AuthnRequest AssertionConsumerServiceURL="http://myserviceprovider:8000/saml/acs" 
        Destination="https://oktapreview.com/app/myserviceprovider/k40ctg3zVVFQYUMEJFTB/sso/saml" 
        ID="id-02a0e2290bbc7fda421483af6b02a9a5" IssueInstant="2015-01-20T22:57:02Z"
        ProtocolBinding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Version="2.0"
 xmlns:ns0="urn:oasis:names:tc:SAML:2.0:protocol"> 
    <ns1:Issuer Format="urn:oasis:names:tc:SAML:2.0:nameid-format:entity" xmlns:ns1="urn:oasis:names:tc:SAML:2.0:assertion">http://myserviceprovider:8000/metadata.xml</ns1:Issuer> 
    <ns0:NameIDPolicy AllowCreate="true" Format="urn:oasis:names:tc:SAML:2.0:nameid-format:transient"/> 
</ns0:AuthnRequest>
```
Is it possible to change the namespace 'ns0' and 'ns1' to 'saml2p' and 'samlp'?

I am creating the above AuthnRequest using the ```Saml2Client.prepare_for_authenticate``` method.

**Comment by rohe** [comment]
> 2 feb 2015 kl. 03:01 skrev steveroger <notifications@github.com>:
> 
> All the SAML requests/responses that I am able to generate are formatted with a namespace prefix of "ns0", or "ns1". The IdP that I am using requires the namespace prefix to be ’saml2p' or 'samlp' instead.

That IdP is broken !
That statement probably does not help you :-)

> For example, here is an AuthnRequest that I generate using the pysaml2 library:
> 
> <ns0:AuthnRequest AssertionConsumerServiceURL="http://myserviceprovider:8000/saml/acs"
>         Destination="https://oktapreview.com/app/myserviceprovider/k40ctg3zVVFQYUMEJFTB/sso/saml"
>         ID="id-02a0e2290bbc7fda421483af6b02a9a5" IssueInstant="2015-01-20T22:57:02Z"
>         ProtocolBinding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Version="2.0"
>  xmlns:ns0="urn:oasis:names:tc:SAML:2.0:protocol">
>     <ns1:Issuer Format="urn:oasis:names:tc:SAML:2.0:nameid-format:entity" xmlns:ns1="urn:oasis:names:tc:SAML:2.0:assertion">http://myserviceprovider:8000/metadata.xml</ns1:Issuer>
>     <ns0:NameIDPolicy AllowCreate="true" Format="urn:oasis:names:tc:SAML:2.0:nameid-format:transient"/>
> </ns0:AuthnRequest>
> 
> Is it possible to change the namespace ’ns0' and 'ns1' to 'saml2p' and 'samlp'?

Not in an easy way.
If you’re signing your request then I would say it’s too complicated right now.
If you’re not there is a modification you can do to the code.
I might bring this into the main branch but not right now and when and if I do it will work also for signed requests.

Anyway back to the what you can do.

> I am creating the above AuthnRequest using the Saml2Client.prepare_for_authenticate method.

There is this line (line 74 in my version) in prepare_for_authenticate:

_req_str = ”%s” % req

if you rewrite it to be:

_req_str = req.to_string(nspair={”saml2": saml.NAMESPACE, ”saml2p”: samlp.NAMESPACE})

you should get what you want.

- Roland

"It is the consequence of humanity. We are all formed of frailty and error; let us pardon reciprocally each others’ folly - that is the first law of nature.” - Voltaire

**Comment by rohe** [comment]
Checked in fix that allows you to give name space prefixes as argument to prepare_for_authenticate.

**Comment by steveroger** [comment]
Thanks for the help and the fix. Everything worked as expected.
