### ISSUE TITLE
Security bypass by using invalid destination or unexpected ID

### ISSUE THREAD

**Issue by ehsanf** [rohe/pysaml2#185]
There is a security bug that allows you to bypass many sanity checks by setting a wrong value for destination or a mismatch response ID. See this code snippet:

From response.py:

``` python
    class StatusResponse(object):
    ....
        def _verify(self):
            if self.request_id and self.in_response_to and \
                            self.in_response_to != self.request_id:
                logger.error("Not the id I expected: %s != %s" % (
                    self.in_response_to, self.request_id))
                return None

            try:
                assert self.response.version == "2.0"           #<<<<< These checks can be bypassed
            except AssertionError:
                _ver = float(self.response.version)
                if _ver < 2.0:
                    raise RequestVersionTooLow()
                else:
                    raise RequestVersionTooHigh()

            if self.asynchop:
                if self.response.destination and \
                        self.response.destination not in self.return_addrs:
                    logger.error("%s not in %s" % (self.response.destination,
                                                   self.return_addrs))
                    return None

            assert self.issue_instant_ok()           #<<<<< These checks can be bypassed
            assert self.status_ok()           #<<<<< These checks can be bypassed
            return self

    class AuthnResponse(StatusResponse):
    ....
        def verify(self):
            """ Verify that the assertion is syntactically correct and
            the signature is correct if present."""

            try:
                self._verify()  #<<<<<<< This is where a None return is ignored.
            except AssertionError:
                return None

            if self.parse_assertion():
                return self  #<<<<<<<< And later if it is parsable, even if there were errors earlier, it returns a positive response
            else:
                self.log.error("Could not parse the assertion")
                return None
```

This is due to inconsistent error return where a return None is considered a fail for some checks and an exception is considered fail for some other checks. At some point, a caller function assumes all errors to be in form of exceptions, and the "return None" type errors are ignored. This allows a malicious party to skip all the future checks by generating a "return None" error.

**Comment by rohe** [comment]
Checked in a fix. Please verify!

**Comment by ehsanf** [comment]
Reviewed. It looks all good. Can you make a release with the patch in?

**Comment by rohe** [comment]
> 3 feb 2015 kl. 21:01 skrev Ehsan Foroughi <notifications@github.com>:
> 
> Reviewed. It looks all good. Can you make a release with the patch in?

Thanks for the review will do a release now.

- Roland

"It is the consequence of humanity. We are all formed of frailty and error; let us pardon reciprocally each others’ folly - that is the first law of nature.” - Voltaire

**Comment by spaceone** [comment]
Could you describe the impact of that vulnerability? Which configuration is affected. SP or IDP or both?
Which git commit is the fix? Can it easily be backported to version 2?

**Comment by spaceone** [comment]
https://github.com/rohe/pysaml2/commit/d21ac9a70bce0535a2f3cc3a621452ad9d0681d6

**Comment by jkakavas** [comment]
Closing this as it is implemented
