### ISSUE TITLE
Possibly invalid NAMEID_FORMAT_EMAILADDRESS

### ISSUE THREAD

**Issue by dfeinzeig** [rohe/pysaml2#196]
In this file:

https://github.com/rohe/pysaml2/blob/7b025c619ffd187ededb102143eaf6a6c87ee918/src/saml2/__init__.py#L44

is defined "urn:oasis:names:tc:SAML:2.0:nameid-format:emailAddress", but I don't believe that is a valid name format.

but this one appears to be the correct one:

> from saml2.saml import NAMEID_FORMAT_EMAILADDRESS
> NAMEID_FORMAT_EMAILADDRESS
> 'urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress'

**Comment by jkakavas** [comment]
This has been resolved ( https://github.com/rohe/pysaml2/blob/master/src/saml2/__init__.py#L49 )
