### ISSUE TITLE
Possible bug in example?

### ISSUE THREAD

**Issue by serpulga** [rohe/pysaml2#198]
In this line [line](https://github.com/rohe/pysaml2/blob/a4af98d8434c9aada0c8b3a117e3879c6aa5eb99/example/idp2/idp.py#L134):

``` python
            if "Signature" in saml_msg:
                kwargs = {"signature": saml_msg["signature"],
                        "sigalg": saml_msg["SigAlg"]}
```

Checks if the key `Signature` exists inside the `saml_msg` object, but the key `signature` is accessed?, shouldn't this be:

``` python
            if "Signature" in saml_msg:
                kwargs = {"signature": saml_msg["Signature"],
                        "sigalg": saml_msg["SigAlg"]}
```

**Comment by russel1237** [comment]
According to [current code](https://github.com/rohe/pysaml2/blob/master/example/idp2/idp.py#L136), it's been solved. I am going to close this.
