### ISSUE TITLE
multiple top-level modules

### ISSUE THREAD

**Issue by apevec** [rohe/pysaml2#202]
pysaml2 installs multiple top-level modules:
 s2repoze
 saml2
 xmldsig
 xmlenc

In order to package saml2 for Fedora, I need to clarify relationship to https://pypi.python.org/pypi/xmldsig to the module included in pysaml2 since they would conflict and APIs seem to be completely different.
Are xml* and s2repoze modules supposed to be standalone public modules or are they internal implementation details which should be moved under saml2. namespace i.e.
saml2.s2repoze
saml2.xmldsig
saml2.xmlenc
?

**Comment by rohe** [comment]
> 2 apr 2015 kl. 22:13 skrev Alan Pevec <notifications@github.com>:
> 
> pysaml2 installs multiple top-level modules:
> s2repoze
> saml2
> xmldsig
> xmlenc
> 
> In order to create package saml2 for Fedora, I need to clarify relationship to https://pypi.python.org/pypi/xmldsig to the module included in pysaml2 since they would conflict and APIs seem to be completely different.
> Are xml* and s2repoze modules supposed to be standalone public modules or are they internal implementation details which should be moved under saml2. namespace i.e.
> saml2.s2repoze
> saml2.xmldsig
> saml2.xmlenc
> ?

They should be moved.
They are where they are for historical, now not valid, reasons.

I’ll move them.

- Roland

"It is the consequence of humanity. We are all formed of frailty and error; let us pardon reciprocally each others’ folly - that is the first law of nature.” - Voltaire

**Comment by apevec** [comment]
AFAICT this was addressed by https://github.com/rohe/pysaml2/commit/9af3252035484f4a8c624eba0f35b68280d43fd2

**Comment by rohe** [comment]
> 20 maj 2015 kl. 13:02 skrev Alan Pevec <notifications@github.com>:
> 
> AFAICT this was addressed by 9af3252

Correct !

- Roland

"It is the consequence of humanity. We are all formed of frailty and error; let us pardon reciprocally each others’ folly - that is the first law of nature.” - Voltaire

**Comment by apevec** [comment]
BTW this is backward incompatible change so make sure to mention it in future 2.5.0 release notes.
Users will need something like https://review.openstack.org/184445 in OpenStack Keystone to work with both pysaml2 versions.

**Comment by rohe** [comment]
> 20 maj 2015 kl. 13:51 skrev Alan Pevec <notifications@github.com>:
> 
> BTW this is backward incompatible change so make sure to mention it in future 2.5.0 release notes.

So I should probably bump the version to 3.0.0 to stress the incompatible change.

> Users will need something like https://review.openstack.org/184445 in OpenStack Keystone to work with both pysaml2 versions.

Right!

- Roland

"It is the consequence of humanity. We are all formed of frailty and error; let us pardon reciprocally each others’ folly - that is the first law of nature.” - Voltaire

**Comment by apevec** [comment]
Yes, semver.org says 3.0.0 is in order.
