### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by m3nu** [rohe/pysaml2#214]
What's the status of making it work with Python 3? I'd be willing to start working on the conversion/keeping it compatible with both versions, if that is possible.

**Comment by rohe** [comment]
> 6 maj 2015 kl. 04:51 skrev Manuel Riel <notifications@github.com>:
> 
> What's the status of making it work with Python 3? I’d be willing to start working on the conversion/keeping it compatible with both versions, if that is possible.

I just checked using caniusepython3 (https://pypi.python.org/pypi/caniusepython3) and it seems there is no dependencies that
prevents us from porting pysaml2 to python3 so please go ahead.
We should probably fork of a branch where the porting work could be done.

- Roland

"It is the consequence of humanity. We are all formed of frailty and error; let us pardon reciprocally each others’ folly - that is the first law of nature.” - Voltaire

**Comment by manuelRiel** [comment]
Good to know. I'll branch it and have a look around.

**Comment by silverdaz** [comment]
Is that a good place to start? https://docs.python.org/3/howto/pyporting.html

I'm rather inexperienced on SAML.
I'm currently looking at it because I need to connect to SWAMID (and use python3).

Can I help on rushing a bit the porting? (although I'm a beginner on the matter...)
Oh well, I'm gonna learn a lot!

**Comment by rohe** [comment]
> 7 maj 2015 kl. 10:49 skrev Daz <notifications@github.com>:
> 
> Is that a good place to start? https://docs.python.org/3/howto/pyporting.html

I just  ported another of my projects to python3 and I used
http://python-future.org/automatic_conversion.html as the starting point for
that work.
Now it turned out I had/chose to refactor the code quite substantially to get it
really to work. Hopefully we will not have the same need here.

> I'm rather inexperienced on SAML.
> I’m currently looking at it because I need to connect to SWAMID (and use python3).

SWAMID ! Hey you’re in my backgarden then :-)

> Can I help on rushing a bit the porting? (although I'm a beginner on the matter...)
> Oh well, I'm gonna learn a lot!

You sure will :-)

- Roland

"It is the consequence of humanity. We are all formed of frailty and error; let us pardon reciprocally each others’ folly - that is the first law of nature.” - Voltaire

**Comment by silverdaz** [comment]
Hi Roland,

I was wondering about the progress.
On your last commit from yesterday, I see many changes to make it python3 compatible. That's great!
But now I wonder if it is finished and ready for python3...
What do you say? ;)
(and Thanks!)

**Comment by rohe** [comment]
> 19 maj 2015 kl. 19:38 skrev Daz <notifications@github.com>:
> 
> Hi Roland,
> 
> I was wondering about the progress.
> On your last commit from yesterday, I see many changes to make it python3 compatible. That's great!
> But now I wonder if it is finished and ready for python3...
> What do you say? ;)
> (and Thanks!)

It’s not finished, we’ve just taken a couple of steps in the python3 direction :-)

- Roland

"It is the consequence of humanity. We are all formed of frailty and error; let us pardon reciprocally each others’ folly - that is the first law of nature.” - Voltaire

**Comment by SpamapS** [comment]
Just FYI, we landed a ton of fixes recently, and the number of failures in the test suite is down to _6_. Please if you're interested, grab master, run 'python3.4 setup.py test', and see if you can grok those last 6 fails (I cannot, being more of a python interested person than a SAML interested person).

**Comment by rohe** [comment]
> 16 jun 2015 kl. 17:57 skrev SpamapS <notifications@github.com>:
> 
> Just FYI, we landed a ton of fixes recently, and the number of failures in the test suite is down to 6. Please if you're interested, grab master, run 'python3.4 setup.py test', and see if you can grok those last 6 fails (I cannot, being more of a python interested person than a SAML interested person).

It’s in the list of tasks to be done within the near future.

- Roland

"It is the consequence of humanity. We are all formed of frailty and error; let us pardon reciprocally each others’ folly - that is the first law of nature.” - Voltaire

**Comment by shaleh** [comment]
All tests are passing now. Is this work complete?

**Comment by rohe** [comment]
> 23 jul 2015 kl. 03:03 skrev Sean Perry <notifications@github.com>:
> 
> All tests are passing now. Is this work complete?

There are some remaining things with the examples but baring that yes !
Given that the tests are good enough :-/

- Roland

”Capitalism is the extraordinary belief that the nastiest of men for the nastiest of motives will somehow work for the benefit of all" - John Maynard Keynes.

**Comment by trebor74hr** [comment]
What is the status of Python3 compatibility, when you expect this will be released?

**Comment by rohe** [comment]
> 18 feb 2016 kl. 10:35 skrev trebor74hr <notifications@github.com>:
> 
> What is the status of Python3 compatibility, when you expect this will be released?

If you look in the setup.py you see that we support 3.4 and 3.5.
We’ve done so since back at the beginning of the autumn.

— Roland

”Everybody should be quiet near a little stream and listen."
From ’Open House for Butterflies’ by Ruth Krauss

**Comment by shaleh** [comment]
So why is the issue still open?

**Comment by rohe** [comment]
Closed now :-)
