### ISSUE TITLE
automated federated metadata download

### ISSUE THREAD

**Issue by mrbasil** [rohe/pysaml2#216]
Does pysaml2 support automated download of federated metadata?  In particular I'm interested in InCommon metadata.  

Or would I need to write a "loader" and pass it in to the config (I see that referenced in mdstore.py)?

mb

**Comment by rohe** [comment]
> 12 maj 2015 kl. 06:59 skrev mbasil77 <notifications@github.com>:
> 
> Does pysaml2 support automated download of federated metadata? In particular I'm interested in InCommon metadata.
> 
> Or would I need to write a ”loader" and pass it in to the config (I see that referenced in mdstore.py)?

You could if you wanted to but you can also use what’s build in.
In fact when verifying my answer I encountered a bug in handling external sources using the new config format.
I’ve fixed that now, just checked in the fix.

What you can do is the following:

1) Download the InCommon metadata certificate and verify it.
https://spaces.internet2.edu/display/InCFederation/Metadata+Signing+Certificate


2) configure metadata source in the configuration file like this:


”metadata”: [{
    "class": "saml2.mdstore.MetaDataExtern",
    "metadata": [
        ("http://md.incommon.org/InCommon/InCommon-metadata-export.xml",
         "inc-md-cert.pem")]
    }
]

Here I assume you have stored the InCommon certificate in the directory from where you start the IdP.

- Roland

"It is the consequence of humanity. We are all formed of frailty and error; let us pardon reciprocally each others’ folly - that is the first law of nature.” - Voltaire

**Comment by mbasil77** [comment]
Awesome.  Thanks!



Mike Basil
312.436.1083

**Comment by rohe** [comment]
Actually, one caveat. The metadata URL I give in the example below is
pointing to the metadata set that Internet2 is publishing to eduGAIN.

If you want the whole set you should use:

http://md.incommon.org/InCommon/InCommon-metadata.xml

More about different aggregates on https://spaces.internet2.edu/display/InCFederation/Metadata+Aggregates

> 19 maj 2015 kl. 05:50 skrev mbasil77 <notifications@github.com>:
> 
> Awesome. Thanks!
> 
> 
> 
> Mike Basil
> 312.436.1083
> 
> On Fri, May 15, 2015 at 12:35 PM, Roland Hedberg <notifications@github.com>
> wrote:
> 
> >
> > > 12 maj 2015 kl. 06:59 skrev mbasil77 <notifications@github.com>:
> > >
> > > Does pysaml2 support automated download of federated metadata? In
> > particular I'm interested in InCommon metadata.
> > >
> > > Or would I need to write a ”loader" and pass it in to the config (I see
> > that referenced in mdstore.py)?
> >
> > You could if you wanted to but you can also use what’s build in.
> > In fact when verifying my answer I encountered a bug in handling external
> > sources using the new config format.
> > I’ve fixed that now, just checked in the fix.
> >
> > What you can do is the following:
> >
> > 1) Download the InCommon metadata certificate and verify it.
> >
> > https://spaces.internet2.edu/display/InCFederation/Metadata+Signing+Certificate
> >
> >
> > 2) configure metadata source in the configuration file like this:
> >
> >
> > ”metadata”: [{
> > "class": "saml2.mdstore.MetaDataExtern",
> > "metadata": [
> > ("http://md.incommon.org/InCommon/InCommon-metadata-export.xml",
> > "inc-md-cert.pem")]
> > }
> > ]
> >
> > Here I assume you have stored the InCommon certificate in the directory
> > from where you start the IdP.
> >
> > - Roland
> >
> > "It is the consequence of humanity. We are all formed of frailty and
> > error; let us pardon reciprocally each others’ folly - that is the first
> > law of nature.” - Voltaire
> >
> >
> >
> >
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/rohe/pysaml2/issues/216#issuecomment-102465280>.
> >
> —
> Reply to this email directly or view it on GitHub.
> 

- Roland

"It is the consequence of humanity. We are all formed of frailty and error; let us pardon reciprocally each others’ folly - that is the first law of nature.” - Voltaire

**Comment by mbasil77** [comment]
I noticed.  Thanks.

Mike Basil
312.436.1083

**Comment by jkakavas** [comment]
The request seems to be satisfied, so I'm closing this
