### ISSUE TITLE
Version numbers

### ISSUE THREAD

**Issue by kalvish21** [rohe/pysaml2#220]
I was checking out versions of the libraries on my server and realized that the VERSION number is not updated. Is this intentional? Like 2.4 still says 2.0

**Comment by rohe** [comment]
> 20 maj 2015 kl. 18:02 skrev kalvish21 <notifications@github.com>:
> 
> I was checking out versions of the libraries on my server and realized that the VERSION number is not updated. Is this intentional? Like 2.4 still says 2.0

No quite unintentional.

- Roland

"It is the consequence of humanity. We are all formed of frailty and error; let us pardon reciprocally each others’ folly - that is the first law of nature.” - Voltaire

**Comment by jkakavas** [comment]
I thnk @kalvish21 refers to https://github.com/rohe/pysaml2/blob/master/src/saml2/__init__.py#L61 which denotes the SAML version , which is intentionally 2.0
