### ISSUE TITLE
Can pysaml2 support IdP-Initiated SSO?

### ISSUE THREAD

**Issue by josedesoto** [rohe/pysaml2#243]
According with Oasis documentation the IDP can initiate the SSO. Is there any documentation/reference how implement this profile with pysaml2? Here is the Oasis reference:

http://docs.oasis-open.org/security/saml/Post2.0/sstc-saml-tech-overview-2.0-cd-02.html#5.1.4.IdP-Initiated%20SSO:%20%20POST%20Binding|outline

**Comment by sergedomk** [comment]
Yes it does. It's not really any different than dealing with SP initiated SSO. Here is the relevant code for dealing with either copied from Flask-PySAML2:

```python
client = Saml2Client(self._config, identity_cache=identity_cache)
saml_response = client.parse_authn_request_response(
        request.form['SAMLResponse'],
        BINDING_HTTP_POST,
        outstanding=outstanding_queries_cache)
```

**Comment by josedesoto** [comment]
Thanks  sergedomk  for your reply.

As far I could understand for doing  IDP initiate SSO, the IDP is the one who originate the process flow and the one who creates the Response message (Unsolicited SAML Response).  With this assumption I don’t understand why you need request.form['SAMLResponse'] and what it should contain. Looking into the method before it request xmlstr: the reply as a xml string 

```
def parse_authn_request_response(self, xmlstr, binding, outstanding=None...):
        :param xmlstr: The reply as a xml string
```

**Comment by sergedomk** [comment]
My example was from the Flask-PySAML2 library. This specific example is for handling an HTTP POST AuthN response passed in via the Flask request object.

With either SP initiated or IdP initiated, the assertion comes in the form of a SAMLResponse. In the case of the latter, it's sometimes referred to as an unsolicited response.

For the exact syntax of the AuthnResponse, I'd look at the SAML2.0 spec itself.

**Comment by josedesoto** [comment]
This way it works for me...

In my case I do:

1- Create the nameID object.
2- Create the create_authn_response 
3- The last one: apply_binding

A simplified code could be:

```
name_id = self.IDP.ident.get_nameid(self.user, name_id_policy, sp_name_qualifier, name_qualifier)
_resp = self.IDP.create_authn_response(identity, in_response_to, destination, sp_entity_id, userid= self.user, binding=binding, name_id_policy=name_id, **resp_args)
http_args = self.IDP.apply_binding(binding_out,
                                      "%s" % _resp, destination, response=True, **kwargs)
return self.response(binding_out, http_args)
```

identity: dict with all parameters you want to send into the response
destination: The Assertion Consumer Service URL
sp_entity_id: Issuer
name_id_policy: NAMEID_FORMAT_PERSISTENT, NAMEID_FORMAT_EMAILADDRESS, etc
name_qualifier: entityid
binding: it should be BINDING_HTTP_POST

**Comment by parakh10** [comment]
@josedesoto if possible can you please share the code where you have implemented the IDP inisiated process

**Comment by josedesoto** [comment]
Hi @parakh10 ,

In the comment before you have the summary how to do the POST. Note, that the parameters I pass to the functions are according to my code. You have full understand how nameID and create_authn_response works. These functions are self documented in pysaml. Here the code to the post:

1- Create the nameID object.
`name_id = self.IDP.ident.get_nameid(self.user, name_id_policy, sp_name_qualifier, name_qualifier)`

2- Create the create_authn_response
```
_resp = self.IDP.create_authn_response(self.identity, in_response_to, destination, sp_entity_id, userid= self.user, binding=binding, name_id_policy=name_id, **resp_args)
```

3- The last one: apply_binding
```
http_args = self.IDP.apply_binding(binding_out, "%s" % _resp, destination, response=True, relay_state=app.f_relay_state, **kwargs)
```

Finally:

`return http_args['data']`

**Comment by bjm88** [comment]
can someone share a full working example from flask get method ?? This is a big confusing as provided, what is "self" and what are some of the valid values for all the parameters?
