### ISSUE TITLE
documentation <> example mismatch

### ISSUE THREAD

**Issue by spaceone** [rohe/pysaml2#245]
http://pysaml2.readthedocs.org/en/latest/howto/config.html#authn-requests-signed
says
`Valid values are “true” or “false”. Default value is “false”.` for the "authn_requests_signed" configuration. The example in https://github.com/rohe/pysaml2/blob/master/example/sp-wsgi/sp_conf.py.example#L26 uses python-booleans.

Can you please clarify what is really accepted?

**Comment by rohe** [comment]
> 28 jul 2015 kl. 16:42 skrev spaceone <notifications@github.com>:
> 
> http://pysaml2.readthedocs.org/en/latest/howto/config.html#authn-requests-signed
> says
> Valid values are “true” or “false”. Default value is “false”. for the "authn_requests_signed" configuration. The example in https://github.com/rohe/pysaml2/blob/master/example/sp-wsgi/sp_conf.py.example#L26 uses python-booleans.
> 
> Can you please clarify what is really accepted?

It should be python booleans. I’ve changed the docs.
But I’ve also added some code, such that is should handle both.

— Roland
'Look, that's why there's rules, understand? So that you think before you break ’em.’ - Terry Pratchett

**Comment by jkakavas** [comment]
This has been fixed
