### ISSUE TITLE
FedRAMP Compliance for Pysaml2

### ISSUE THREAD

**Issue by nchigwamba** [rohe/pysaml2#250]
Hi, 

I am using Pysaml2 and just wanted to check if there have been efforts to conform to the requirements for Federal Compliance, such as FedRAMP (https://www.fedramp.gov)?

Regards,
Nyasha

**Comment by jkakavas** [comment]
I'm leaning towards closing this as irrelevant

**Comment by rohe** [comment]
I'm with you.
