### ISSUE TITLE
reload configuration?

### ISSUE THREAD

**Issue by spaceone** [rohe/pysaml2#255]
What is the official way to reload the configuration (without starting a new python process)?

```
c = saml2.client.Saml2Client(config_file='/usr/share/saml/sp.py')
# ... some time pass ...
c = saml2.client.Saml2Client(config_file='/usr/share/saml/sp.py')
# it still uses the old configuration... The module is not imported again.
```

I can workaround this with `sys.modules.pop('sp')` but is there an official way or suggestion?

**Comment by rohe** [comment]
No official way.
