### ISSUE TITLE
1 test failure - missing /Users/rolandh/code/saml2test/tests/idp_test/rainer/idp5PortalverbundGvAt.local/testfed-metadata.xml

### ISSUE THREAD

**Issue by milligana** [rohe/pysaml2#266]
Hi Roland,
Great effort on this library! But I get a single test failure because a local file is missing: maybe incorporate it in the test suite ;)

tests/test_84_entcat.py:88: 

---

src/saml2/mdstore.py:835: in imp
    self.load(key, val)
src/saml2/mdstore.py:821: in load
    _md.load()
src/saml2/mdstore.py:595: in load
    _txt = self.get_metadata_content()

---

self = <saml2.mdstore.MetaDataFile object at 0x7f8aa353e590>

```
def get_metadata_content(self):
```

> ```
>   return open(self.filename).read()
> ```
> 
> E       IOError: [Errno 2] No such file or directory: '/Users/rolandh/code/saml2test/tests/idp_test/rainer/idp5PortalverbundGvAt.local/testfed-metadata.xml'

src/saml2/mdstore.py:592: IOError

**Comment by jkakavas** [comment]
There is no tests/test_84_entcat.py anymore
