### ISSUE TITLE
Crash ('unicode' object has no attribute 'items') after logging into example

### ISSUE THREAD

**Issue by isaaclw** [rohe/pysaml2#271]
I cloned the repository, made a virtual environment, and ran 'pip install setup.py' to install pysaml2 in the virtual environment.

Then I switched to the example folder, and started the server.

Login worked fine (on 8088), but when it redirects to 8087, and I get an error:

'unicode' object has no attribute 'items'

I don't see any line numbers, so I don't know how to debut what's causing the crash. The browser returns a 500 error, so I'm assuming that my blank page isn't expected.

**Comment by rohe** [comment]
> 16 okt 2015 kl. 21:19 skrev isaaclw <notifications@github.com>:
> 
> I cloned the repository, made a virtual environment, and ran 'pip install setup.py' to install pysaml2 in the virtual environment.
> 
> Then I switched to the example folder, and started the server.
> 
> Login worked fine (on 8088), but when it redirects to 8087, and I get an error:
> 
> 'unicode' object has no attribute 'items'
> 
> I don't see any line numbers, so I don't know how to debut what's causing the crash. The browser returns a 500 error, so I’m assuming that my blank page isn't expected.

Python 2 or 3 ?

— Roland
'Look, that's why there's rules, understand? So that you think before you break ’em.’ - Terry Pratchett

**Comment by isaaclw** [comment]
rohe: It's python 2.7

**Comment by rohe** [comment]
> 26 okt 2015 kl. 05:53 skrev tpazderka <notifications@github.com>:
> 
> rohe: It’s python 2.7

OK, so I ran the latest code that’s on github and had no problems.
Might be time for a new release.

— Roland
'Look, that's why there's rules, understand? So that you think before you break ’em.’ - Terry Pratchett

**Comment by isaaclw** [comment]
Sorry, I didn't quite understand what you meant. I'll try to duplicate this again with the latest version, and outline step by step what I was experiencing.

I haven't had a chance to look at the example again recently, though now that I've dived into the code a bit more it's not as critical to me.

It's quite likely that I was just confused about how the example was supposed to work.
