### ISSUE TITLE
Provide config at runtime (different in each request) without file

### ISSUE THREAD

**Issue by rskumar** [rohe/pysaml2#273]
Couldn't find a way to dynamically supply config dictionary at runtime, which may have different SP and IdP data. Can pysaml2 be used in a way without providing everything upfront unlike in example file config is predefined. 
With this approach, SP metadata, saml client config etc would be different for each request, and will be easy to support multi-tenant different SAML provider without restarting server.

**Comment by j0hnsmith** [comment]
There's an example in #203.
