### ISSUE TITLE
Any way to specify a custom NameFormat in the Attribute?

### ISSUE THREAD

**Issue by lzen** [rohe/pysaml2#274]
Hi,

I'm setting up an IdP and one SP requests to set the NameFormat in the Attribute to be a custom value like "www.abcd.com". I tried setting the name_form value in CONFIG(under service.idp.policy.sp_entityid, and also tried setting in default), but it look like it's not picked up and the NameFormat is always NAME_FORMAT_URI ("urn:oasis:names:tc:SAML:2.0:attrname-format:uri"). What's the correct way to set NameFormat?

Thanks for the help!

**Comment by spaceone** [comment]
→ is this the same as https://github.com/rohe/pysaml2/issues/253 ?

**Comment by lzen** [comment]
I think they are different. I'm setting up IdP, and this issue is about how I can specify a custom NameFormat for the attributes in my SAML response to the SP. The name_form parameter in CONFIG idp policy part is supposed to serve this purpose I guess, but somehow it is not working.

**Comment by rohe** [comment]
OK, fixed this one.
Was a spelling error you could say.

> 29 okt 2015 kl. 13:56 skrev landscape-bot <notifications@github.com>:
> 
> I think they are different. I'm setting up IdP, and this issue is about how I can specify a custom NameFormat for the attributes in my SAML response to the SP. The name_form parameter in CONFIG idp policy part is supposed to serve this purpose I guess, but somehow it is not working.
> 
> —
> Reply to this email directly or view it on GitHub.
> 

— Roland
'Look, that's why there's rules, understand? So that you think before you break ’em.’ - Terry Pratchett
