### ISSUE TITLE
SP initated sso

### ISSUE THREAD

**Issue by pradyumnak** [rohe/pysaml2#297]
I am not able to grasp the SP initated SSO using pySAML2. I saw the documentation and example but not sure as I do not found them very intuitive(probably coz I am new to this). Can you guys please brief me in Nutshell, what all API I need to use to initiate the SSO process?

**Comment by josedesoto** [comment]
Hi pradyumnak,

Are you trying to develop a SP or an IDP?

If you have already an external IDP, you can use this example: https://github.com/josedesoto/web2py-sp-example it explain how to connect an SP to a external IDP. It is the SP-Initiated SSO: Redirect/POST Bindings profile. It use web2py framework and pysaml2. 

Here the code to create the SP initiated: 

https://github.com/web2py/web2py/blob/master/gluon/contrib/login_methods/saml2_auth.py

In any case, there are a few examples in the pysaml2 repository.

I hope it helps...
