### ISSUE TITLE
pycrypto has stopped development, we should switch to pycryptodome

### ISSUE THREAD

**Issue by erickt** [rohe/pysaml2#304]
According to https://github.com/dlitz/pycrypto/issues/173, pycrypto has stopped development, and has been forked into [pycryptodome](https://github.com/Legrandin/pycryptodome). It supposedly still supports Python 2.4+ and seems to be relatively actively developed.

**Comment by rohe** [comment]
Agree that we should switch to pycryptodome.

> 20 jan 2016 kl. 04:50 skrev Erick Tryzelaar <notifications@github.com>:
> 
> According to dlitz/pycrypto#173, pycrypto has stopped development, and has been forked into pycryptodome. It supposedly still supports Python 2.4+ and seems to be relatively actively developed.
