### ISSUE TITLE
IDP Certificate Validation on SP (SP developed using pysaml2)

### ISSUE THREAD

**Issue by rishabj** [rohe/pysaml2#316]
Our application acts as an SP developed using PySaml2. For single-sign on, the SP tries to connect to external IDP and fetch SAML response. The SP contains the public certificate of the IDP. I am unable to figure the parameter in which the public certificate of IDP needs to be passed to Pysaml2 for certificate validation. Does pysaml2 support IDP certificate validation ? If yes, how to do that ?

**Comment by rohe** [comment]
> 18 feb 2016 kl. 10:15 skrev rishabj <notifications@github.com>:
> 
> Our application acts as an SP developed using PySaml2. For single-sign on, the SP tries to connect to external IDP and fetch SAML response. The SP contains the public certificate of the IDP. I am unable to figure the parameter in which the public certificate of IDP needs to be passed to Pysaml2 for certificate validation. Does pysaml2 support IDP certificate validation ?

The simple answer is No !

There a quite a number of IdPs that don’t use ’proper’ X.509 certificates so it would break things
if psyaml2 started doing certificate validation.

— Roland

”Everybody should be quiet near a little stream and listen."
From ’Open House for Butterflies’ by Ruth Krauss
