### ISSUE TITLE
Import error with 4.0.4

### ISSUE THREAD

**Issue by therve** [rohe/pysaml2#320]
Seen in CI for now: 

from saml2 import client_base
....
ImportError: No module named future.backports.urllib.parse

I don't see the future dependency declared anywhere? Is it pulled by another package?

Thanks.

**Comment by mriedem** [comment]
This is the failure in the openstack kilo branch CI:

http://logs.openstack.org/66/278466/8/check/gate-heat-dsvm-functional-orig-mysql-lbaasv1/26b4f7d/logs/apache/keystone.txt.gz#_2016-03-09_14_12_14_814037

We don't even have the future pip in our pip freeze:

http://logs.openstack.org/66/278466/8/check/gate-heat-dsvm-functional-orig-mysql-lbaasv1/26b4f7d/logs/pip-freeze.txt.gz

**Comment by mriedem** [comment]
Odd, I don't even see the future import in here:

https://github.com/rohe/pysaml2/blob/e82c319d834ba3b1f5660b7c11de20186b09ff8a/src/saml2/sigver.py

**Comment by mriedem** [comment]
This has to be the breaking change:

https://github.com/rohe/pysaml2/commit/c78a93298c1c4d6063eaad4ad036ce281631d882

But that is unreleased from what I can tell.

**Comment by rohe** [comment]
Pushed a fix to github, will push a new version to PyPi.

> 9 mar 2016 kl. 15:47 skrev Matt Riedemann <notifications@github.com>:
> 
> This has to be the breaking change:
> 
> c78a932
> 
> But that is unreleased from what I can tell.
> 
> —
> Reply to this email directly or view it on GitHub.
> 

— Roland

”Everybody should be quiet near a little stream and listen."
From ’Open House for Butterflies’ by Ruth Krauss
