### ISSUE TITLE
Old version of pysaml2 docs still out there on pythonhosted

### ISSUE THREAD

**Issue by gene1wood** [rohe/pysaml2#327]
In Issue #93 it looks like the docs were moved from pythonhosted.org to pysaml2.readthedocs.org. Unfortunately, all the google juice still goes to pythonhosted.org which holds docs for pysaml 0.4.3 and so when searching for pysaml2 docs, users end up in a confusing state, looking at long outdated docs for the project.

Is there any way to have the pythonhosted.org docs taken down?

**Comment by c00kiemon5ter** [comment]
https://pythonhosted.org/pysaml2/ seems to be down. 
This can be closed.

**Comment by gene1wood** [comment]
Yup, that URL now 404's which is great.
