### ISSUE TITLE
Current documentation version is either outdated or release variable is incorrect

### ISSUE THREAD

**Issue by gene1wood** [rohe/pysaml2#328]
Currently, the docs have a release variable of [1.2.0beta](https://github.com/rohe/pysaml2/blob/9c04dc7ebbae1791b4234bc0f4f2949f1fe9f3c4/doc/conf.py#L52). Are the docs out of date (and not in sync with the current release of pysaml2 (version 4.0.4)? Or are the docs up to date and the release variable is wrong?

The impact of this is that when searching for and [viewing the docs](https://pysaml2.readthedocs.org/en/latest/) they show as being for a very different version of the code than the user would be using. This version (`1.2.0beta`) shows up both in the docs and in search results pointing to the docs.

Combined with Issue #327 the end result is that when the users searches for docs for pysaml2 `4.0.4`, they have to choose between docs for `0.4.3` or `1.2.0beta` which you can imagine is confusing.

**Comment by c00kiemon5ter** [comment]
The documentation should be updated hand in hand with the code updates. Hopefully things are better nowadays. 

I will close this, but feel free to reopen if you find something that needs to be updated (or even better open a PR). 

Thanks.

**Comment by gene1wood** [comment]
@c00kiemon5ter I don't have rights to re-open this ticket so I'll open a new ticket as this problem still exists.

The version number in the docs is still [1.2.0beta](https://github.com/rohe/pysaml2/blob/9c04dc7ebbae1791b4234bc0f4f2949f1fe9f3c4/doc/conf.py#L52). There haven't been any commits that would change the version number since @rohe [set the version in October 2014](https://github.com/rohe/pysaml2/commit/f05587c9111297ec591755382a71f1ea66cc8015). The intent of this value is to be "[the major project version](http://www.sphinx-doc.org/en/stable/config.html#confval-version)" of the software for which the documentation applies.

So assuming the documentation in the head of master applies to the current [version `4.5.0`](https://github.com/rohe/pysaml2/blob/847e970c5af6a09de61307be3a3d0305eee131f7/src/saml2/__init__.py#L20) of pysaml2, then the "version" and "[release](http://www.sphinx-doc.org/en/stable/config.html#confval-release)" values should be `4.5.0`
