### ISSUE TITLE
CryptoBackendXMLSecurity does not specify the ID attribute

### ISSUE THREAD

**Issue by dobesv** [rohe/pysaml2#332]
At some point `CryptoBackendXmlSec1` was updated to specify `--id-attr` when invoking `xmlsec1`.  However the `CryptoBackendXMLSecurity` class doesn't specify this, so SAML assertions that rely on ID lookups will fail with the `CryptoBackendXMLSecurity` whereas they would work with `CryptoBackendXmlSec1`.

I believe it needs to call `xmlAddID` to get the equivalent behavior as `--id-attr` when calling the xmlsec API directly.

See also:
- https://www.aleksey.com/xmlsec/faq.html#section_3_2

**Comment by dobesv** [comment]
Hmm actually on probing the PyXMLSecurity source code it seems to try to handle the ID attribute itself.  Yet, when using the PyXMLSecurity backend to verify signatures we are getting the same symptoms we'd get if we try to use xmlsec1 from the command-line without the `--id-attr` parameter.  So, this might be a bug in PyXMLSecurity moreso than a change required in PySAML2.

**Comment by leifj** [comment]
did you use the setID call in pyXMLSecurity?

**Comment by dobesv** [comment]
@leifj Sorry, I'm not on that project any more, and I don't remember any more!  Perhaps someone who cares about this issue will report it again some day.
