### ISSUE TITLE
Pysaml2 SP with OpenAM IdP

### ISSUE THREAD

**Issue by anishnarang** [rohe/pysaml2#340]
I have a sample SP using Flask and pysaml2. I have setup OpenAM as the IdP and want to integrate it with the SP. Is there any documentation for this available?

**Comment by arvindsree** [comment]
I had tried the same. Looks like OpenAM and pysaml2 are incompatible(Authn request part). 

One work around that I did was to  capture the authn request from Openam SP to Openam IDP and manually send the same. The response can still be parsed with pysaml2 API's

**Comment by rohe** [comment]
What do you mean by incompatible ?
Is pysaml2 not able to read/understand what OpenAM is sending or is it the other way around ?

**Comment by arvindsree** [comment]
The other way around. OpenAM rejects the pysaml2 authn request

**Comment by rohe** [comment]
Do you know what the error message is ?
What's it complaining about ?

**Comment by arvindsree** [comment]
This was the error from the log message

ERROR: NameIDTypeImpl.processElement(): name identifier is missing
libSAML2:09/21/2016 05:01:49:118 PM PDT: Thread[http-bio-8080-exec-8,5,main]: TransactionId[9b179e52-c562-4134-8148-3cdfb9bddc1c-45]
ERROR: IDPSSOFederate.getAuthnRequest(): cannot construct a AuthnRequest object from the SAMLRequest value:
com.sun.identity.saml2.common.SAML2Exception: The name identifier is missing or an empty string
        at com.sun.identity.saml2.assertion.impl.NameIDTypeImpl.getValueAndAttributes(NameIDTypeImpl.java:210)

**Comment by arvindsree** [comment]
This was the authn xml that was originally sent by pysaml2
```
<?xml version='1.0' encoding='UTF-8'?>
<ns0:AuthnRequest
    xmlns:ns0="urn:oasis:names:tc:SAML:2.0:protocol"
    xmlns:ns1="urn:oasis:names:tc:SAML:2.0:assertion" AssertionConsumerServiceURL="http://sxxxxx" Destination="http:xxxx" ID="id-QIIC3MA46oTWyH4up" IssueInstant="2016-09-20T23:09:25Z" ProtocolBinding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Version="2.0">
    <ns1:Issuer Format="urn:oasis:names:tc:SAML:2.0:nameid-format:entity" />
    <ns0:NameIDPolicy AllowCreate="false" Format="urn:oasis:names:tc:SAML:2.0:nameid-format:transient" />
</ns0:AuthnRequest>
```



This was the one openam SP was using
```
<?xml version='1.0' encoding='UTF-8'?>
<samlp:AuthnRequest
    xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol"
ID="$ID" Version="2.0" IssueInstant="$Time" Destination="$Dest" ForceAuthn="false" IsPassive="false" ProtocolBinding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" AssertionConsumerServiceURL="$ACS">
    <saml:Issuer
        xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion">$Issuer
    </saml:Issuer>
        <samlp:NameIDPolicy
        xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol" Format="urn:oasis:names:tc:SAML:2.0:nameid-format:transient" SPNameQualifier="$SPNameQualifier" AllowCreate="true">
    </samlp:NameIDPolicy>
    <samlp:RequestedAuthnContext
        xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol" Comparison="exact">
        <saml:AuthnContextClassRef
            xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion">urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport
        </saml:AuthnContextClassRef>
    </samlp:RequestedAuthnContext>
</samlp:AuthnRequest>
```


Hope this helps

**Comment by rohe** [comment]
If I interpret the error correctly it's complaining about there being no issuer.
This is not a problem with pysaml2 as such, it depends on how the AuthnRequest constructing method was called. Could you send me the relevant code ?

**Comment by arvindsree** [comment]
This was the original command that was used
 reqid, info = saml_client.prepare_for_authenticate() 

I had tried different combinations of the following arguments to the call but those were not accepted as well
#nameid_format=NAMEID_FORMAT_PERSISTENT,allow_create=True,sign=False,bind=BINDING_HTTP_POST,provider_name="#$@#$@")

**Comment by rohe** [comment]
> On 03 Nov 2016, at 21:49, Arvind <notifications@github.com> wrote:
> 
> This was the original command that was used
> reqid, info = saml_client.prepare_for_authenticate()
> 
> I had tried different combinations of the following arguments to the call but those were not accepted as well
> #nameid_format=NAMEID_FORMAT_PERSISTENT,allow_create=True,sign=False,bind=BINDING_HTTP_POST,provider_name="#$@#$@"
> 
> 

Look at test_51_client.py in the distribution.

If you combine setup_class and test_do_authn you should get something that you could test with against OpenAM.

— Roland

**Comment by arvindsree** [comment]
I will try that after a while, since the workaround is working for me now

**Comment by sergedomk** [comment]
I'm also having this issue with OpenAM. I was informed that the issue was not with the Issuer but rather with the namespacing (i.e., ns0 and ns1 should be saml and samlp respectively). See http://docs.oasis-open.org/security/saml/v2.0/saml-core-2.0-os.pdf#page=7

I was informed that OpenAM is very strict concerning conformance with the specification and have verified that simply changing the namespace on the requests was sufficient to get OpenAM to accept it.

**Comment by sergedomk** [comment]
We've discovered that there is a rather simple workaround for the issue with the improper namespacing. It should be noted that the namespace is not directly an issue with PySAML2. It comes from xml.etree. To correct the namespacing for PySAML2 so that it is compliant with OpenAM the nsprefix should be set explicitly.

```
  (session_id, result) = client.prepare_for_authenticate(
      entityid=idp_entityid,
      relay_state=next_url,
      sign=self._config.getattr('authn_requests_signed'),
-     binding=binding)
+     binding=binding,
+     nsprefix={'saml': 'urn:oasis:names:tc:SAML:2.0:assertion',
+               'samlp': 'urn:oasis:names:tc:SAML:2.0:protocol'})
```

**Comment by jkakavas** [comment]
I disagree with what OpenAM regards as conformance to the specification. The http://docs.oasis-open.org/security/saml/v2.0/saml-core-2.0-os.pdf#page=7 only states that "Conventional XML namespace prefixes are used throughout the listings in this specification to stand for their respective namespaces (see Section 1.2) as follows, whether or not a namespace declaration is present in the example:"

It doesn't declare these namespaces as normative or obligatory, it just gives an example. 

The namespaces prefixes that pysaml2 uses by default, although not the "conventional" ones are properly declared so any compliant implementation should be able to consume the Authentication Request.

If on objections, I will close this issue
