### ISSUE TITLE
How do I configure an SP to load remote metadata from an IdP that uses separate signing and encryption keys?

### ISSUE THREAD

**Issue by kgodey** [rohe/pysaml2#342]
In the example given, remote metadata only has one `cert` parameter. How do I configure it to use separate signing and encryption certs? Is this supported?

``` python
"metadata" : {
    "remote": [
        {
            "url":"https://kalmar2.org/simplesaml/module.php/aggregator/?id=kalmarcentral2&set=saml2",
            "cert":"kalmar2.cert"
        }],
},
```

**Comment by jkakavas** [comment]
I think you have

The `cert` parameter refers to the certificate that contains the public key that is used for signing the metadata document. There is no encryption key as metadata documents are generally not encrypted. 

I guess you are referring to encryption/signing keys support for specific SAML entities. If any of the  SAML entities that are described in the metadata has different signing and encryption keys , it should denote that within its EntityDescriptor with the proper use of `use=` attributes and pysaml2 will be able to understand that.
