### ISSUE TITLE
Identity cache corruption with s2repoze SP plugin

### ISSUE THREAD

**Issue by MrkGrgsn** [rohe/pysaml2#373]
I'm seeing irregular corruption of the identity cache used by `Saml2Client`. This is accompanied by errors:

> DBRunRecoveryError: (-30974, 'DB_RUNRECOVERY: Fatal error, run database recovery -- PANIC: fatal region error detected; run recovery')

I am using pysaml2 4.0.0 with CKAN running in mod_wsgi with apache 2.4.16 prefork and python 2.7.12.  The `saml2.cache` module uses python shelves, which is defaulting to using Berkely DB.

The Python documentation for shelve states 'The shelve module does not support concurrent read/write access to shelved objects.' https://docs.python.org/2/library/shelve.html#restrictions, which makes me think it's a concurrency issue. 

I'm interested to hear whether anyone else has experienced this issue.

I see that the `Cache` class falls back to caching identities in memory if an identity cache file path is not configured, which being per-process would not result in a shared cache like shelves would. Roland, can you please advise if this would change functionality and whether it would be a safe workaround?

**Comment by rohe** [comment]
> On 24 Oct 2016, at 16:54, Mark Gregson <notifications@github.com> wrote:
> 
> I'm seeing irregular corruption of the identity cache used by Saml2Client. This is accompanied by errors:
> 
> DBRunRecoveryError: (-30974, 'DB_RUNRECOVERY: Fatal error, run database recovery -- PANIC: fatal region error detected; run recovery')
> 
> I am using pysaml2 4.0.0 with CKAN running in mod_wsgi with apache 2.4.16 prefork and python 2.7.12. The saml2.cache module uses python shelves, which is defaulting to using Berkely DB.
> 
> The Python documentation for shelve states 'The shelve module does not support concurrent read/write access to shelved objects.' https://docs.python.org/2/library/shelve.html#restrictions <https://docs.python.org/2/library/shelve.html#restrictions>, which makes me think it's a concurrency issue.
> 
> I'm interested to hear whether anyone else has experienced this issue.
> 
Haven't seen it myself.
> I see that the Cache class falls back to caching identities in memory if an identity cache file path is not configured, which being per-process would not result in a shared cache like shelves would. Roland, can you please advise if this would change functionality and whether it would be a safe workaround?
> 
Should not change functionality.
I think it’s worth testing, should be safe.

— Roland

**Comment by MrkGrgsn** [comment]
Thanks @rohe we'll test the in memory caching.

**Comment by MrkGrgsn** [comment]
We've been running this with in-memory caching for a couple of months now and is running just fine. No corruption, of course, and no other side-effects we've observed.

**Comment by rp-21** [comment]
Hi @MrkGrgsn 
so how did it solve for you.
this happening for me only for one user.

**Comment by MrkGrgsn** [comment]
@rp-21 I don't work on that project any more but I think we just did what I mentioned in my comment above, ie, don't configure an identity cache file path.

**Comment by shevron** [comment]
We're seeing the same issue, but with `sid_storage` and not `identity_cache`. It seems to me that relying on `shelve` in a concurrent Web environment is problematic, or am I missing something basic here? 

What can we expect if we also use in-memory storage for `sid_storage`? Should it be side-effect free like with `identity_cache` or can this be a problem?
