### ISSUE TITLE
Why does NCName only match a-zA-Z for the first character?

### ISSUE THREAD

**Issue by isaaclw** [rohe/pysaml2#374]
I'm not sure if this is my fault as a programmer, or the SAML provider I'm connecting to's fault.

I'm getting back ID's that start with a number:
1ORZ+LQ7YktMlk7RMJR+N+by1.foo-bar

The saml looks like this:

```
<ns0:Response xmlns:ns0="urn:oasis:names:tc:SAML:2.0:protocol" xmlns:ns1="urn:oasis:names:tc:SAML:2.0:assertion" xmlns:ns2="http://www.w3.org/2001/04/xmlenc#" xmlns:ns3="http://www.w3.org/2000/09/xmldsig#" Destination="<local development environment>" ID
="1ORZ+LQ7YktMlk7RMJR+N+by1.foo-bar" InResponseTo="<idp url>" IssueInstant="2016-10-25T22:57:46.961Z" Version="2.0">
```

I'm getting a crash when it tries to validate the ncname:

https://github.com/rohe/pysaml2/blob/master/src/saml2/validate.py#L44

Is there a reason it's not supposed to start with a digit? perhaps it's expected to start with 'http://' ?

**Comment by isaaclw** [comment]
Any thoughts? Do you need more info?

**Comment by isaaclw** [comment]
No one to even tell me I'm an idiot and to only use tools I'm familiar with, or to RTFM?

I've since patched the library for our own personal use to also allow numerics at the beginning of the string, but I would really like to follow the standard SAML library where possible.
So knowing why we're having this error would be really helpful.

Thanks in advance.

**Comment by jkakavas** [comment]
Hi, in section 1.3.4 of [SAML Core](https://docs.oasis-open.org/security/saml/v2.0/saml-core-2.0-os.pdf) :
>The xs:NCName simple type is used in SAML to reference identifiers of type xs:ID since xs:IDREF
cannot be used for this purpose. 

Now, an NCNAME is 

` 4] | NCName | ::= | Name - (Char* ':' Char*) | /* An XML Name, minus the ":" */ -- | -- | -- | -- | --  ` [[1]](https://www.w3.org/TR/REC-xml-names/#NT-NCName)

Now `Name` is defined as 
`[5] | Name | ::= | NameStartChar (NameChar)* -- | -- | -- | --` [[2]](https://www.w3.org/TR/REC-xml/#NT-Name) 

and NameStartChar does not contain numbers as seen in 
`[4] | NameStartChar | ::= | ":" \| [A-Z] \| "_" \| [a-z] \| [#xC0-#xD6] \| [#xD8-#xF6] \| [#xF8-#x2FF] \| [#x370-#x37D] \| [#x37F-#x1FFF] \| [#x200C-#x200D] \| [#x2070-#x218F] \| [#x2C00-#x2FEF] \| [#x3001-#xD7FF] \| [#xF900-#xFDCF] \| [#xFDF0-#xFFFD] \| [#x10000-#xEFFFF]
-- | -- | -- | --` [[3]](https://www.w3.org/TR/REC-xml/#NT-NameStartChar)

I hope this clarifies the issue

**Comment by isaaclw** [comment]
It does. Thanks.

I will pass this on to the developer on the other end of our SAML connection.
