### ISSUE TITLE
How to configure ForceAuthn="true" using SAML Client

### ISSUE THREAD

**Issue by ravindrabhavanam** [rohe/pysaml2#391]
I am creating the SAML Request using the below code. I am trying to figure out how to set ForceAuthn attribute in AuthnRequest. 

from saml2.client import Saml2Client
from saml2.config import Config as Saml2Config

spConfig = Saml2Config()
spConfig.load(settings)
saml_client = Saml2Client(config=spConfig)
saml_client.prepare_for_authenticate()

I see one attribute 'force_authn' of samlp. But, i couldn't figure out how to set this attribute using above method. Could you point me to any example or documentation for this?

**Comment by c00kiemon5ter** [comment]
As per #431 there is now an sp configuration option to set `force_authn`. 
I am closing this as resolved.
