### ISSUE TITLE
PySAML vulnerable to signature stripping by default

### ISSUE THREAD

**Issue by terite** [rohe/pysaml2#424]
The the default value for `WantAssertionsSigned` is true in metadata, the default value for `want_assertions_signed` is false. While [the default value of false is documented](https://github.com/rohe/pysaml2/blob/master/doc/howto/config.rst#want-assertions-signed), the discrepancy gives a false sense of security.

Additionally and most importantly, **false is an exceptionally terrible default**. Allowing unsigned assertions is the type of issue that [costs companies _real money_ when found in a bug bounty](http://www.economyofmechanism.com/github-saml#signature-stripping) and is much more costly if found by a real attacker.

**Comment by spaceone** [comment]
There is also "authn_requests_signed", "logout_requests_signed" and maybe others?!. What about them? What's the default and are they documented?

**Comment by spaceone** [comment]
https://github.com/rohe/pysaml2/blob/master/doc/howto/config.rst#logout-requests-signed
→ default: False
https://github.com/rohe/pysaml2/blob/master/doc/howto/config.rst#authn-requests-signed
→ default: True

**Comment by jkakavas** [comment]
> The the default value for WantAssertionsSigned is true in metadata, the default value for want_assertions_signed is false. While the default value of false is documented, the discrepancy gives a false sense of security.

The default value of WantAssertionsSigned in metadata is `False`. That is if the optional element WantAssertsionsSigned is not included in the metadata, then the IdP should assume it is `False` ( https://docs.oasis-open.org/security/saml/v2.0/saml-metadata-2.0-os.pdf  line 743 ) 

`want_assertions_signed` controls the WantAssertionsSigned element in the SP metadata and its default is False, as per the the spec. Now in [metadata.py](https://github.com/rohe/pysaml2/blob/master/src/saml2/metadata.py#L46) the default value is `True` which will create SP metadata that have `WantAssertionsSigned=True` . 

While I agree there is a discrepancy and needs to be cleared out in documentation, why would you say that this causes a false sense of security ? If something it forces `WantAssertionsSigned=True` which will make a conforming IdP to sign the Assertion in the SAML response it will return to this SP. 

Regarding the default, now, assertions *can* be unsigned, as long as the SAML request is signed. See the current version of the [spec](https://www.oasis-open.org/committees/download.php/56782/sstc-saml-profiles-errata-2.0-wd-07.pdf) 

> For the purposes of the profile, either the <Response> or the <Assertion> element(s) in the
<Response> MUST be signed, if the HTTP POST binding is used, and MAY be signed if the HTTP-Artifact binding is used. If an <EncryptedAssertion> element is present and a CBC-mode algorithm is used, then the <Response>SHOULD be signed to ensure the ciphertext is integrity protected (see section 6.2 of [SAMLCore]).

So, if we are to do something, it would be probably better to change `sign_responses` to `True` by default instead, at https://github.com/rohe/pysaml2/blob/master/src/saml2/server.py . On the other hand, if we take pysaml2 for what it is ( a SAML2 implementation in python and not a standalone SAML2 Service Provider implementation that conforms to a profile), I don't know how much sense it makes to enforce defaults in code.

**Comment by jkakavas** [comment]
I stand corrected. `want_assertions_signed` is also used as a flag for whether unsigned assertions are allowed to be consumed by the SP.
Furthermore, there is the undocumented `want_response_signed` parameter ( https://github.com/rohe/pysaml2/blob/master/src/saml2/config.py#L66 ) which is alse False by default and controls whether an SP will accept unsigned SAML responses. 

The current best practice is to sign SAML responses and not the assertions so I suggest we make this explicit in the documentation and include the `want_response_signed` . Regarding changing this default value, I am pro setting this to true in all examples and mark it as important in the docs, but I am not entirely sure on what we should do with the default value in pysaml2 src

**Comment by terite** [comment]
Thank you for your response, @jkakavas!

> used as a flag for whether unsigned assertions are allowed to be consumed by the SP.

This is part of what I meant to convey with my original ticket, thank you for adding & clarifying that!

I do want to push for changing the default value to `True` in code though, for a number of reasons.
1. For users already using pysaml2, the changes to documentation might easily be missed and the issue will persist for them. Users using `pysaml==4.4.x` might not even notice that this change is made.
2. If the documentation marks it important and the default value is True, I think that's a strong sign that the default value in code should be true.
3. I think it's correct to say that "A value of `False` means that users authenticating through SAML can lie about who they are or what privileges they have". For this reason, I do not believe `False` is a correct default value.

**Comment by jkakavas** [comment]
After some additional thought, I fully agree with @terite that this should be set by default. I will add a PR to address this asap
