### ISSUE TITLE
get_local_name throws Exception

### ISSUE THREAD

**Issue by jkakavas** [rohe/pysaml2#441]
`get_local_name` : https://github.com/rohe/pysaml2/blob/master/src/saml2/attribute_converter.py#L245

```
def get_local_name(acs, attr, name_format):
    for aconv in acs:
        #print(ac.format, name_format)
        if aconv.name_format == name_format:
            return aconv._fro[attr]
```

makes the implicit assumption that the attribute converters will contain all attribute OIDs that will be in the required attributes of some services metadata ( we don't check if `attr` is in _fro )

We should either check this here or, handle it with a try clause in 
https://github.com/rohe/pysaml2/blob/master/src/saml2/assertion.py#L82 which is the only place `get_local_name` is used

**Comment by c00kiemon5ter** [comment]
The very [next line](https://github.com/rohe/pysaml2/blob/master/src/saml2/assertion.py#L83) that calls `get_local_name()` checks if the return value was `None`, so the simplest change would be to `return aconv._fro.get(attr)`
