### ISSUE TITLE
v3.0.0 test_41_response.py failing

### ISSUE THREAD

**Issue by kirotawa** [rohe/pysaml2#444]
Hi, 

I'm open this issue in order to get any advice about what/how to fix this issue that happens in version 3.0.0.  Same test pass in upstream version/master version.
Bellow is the error msg while type py.test test_41_response.py

test_41_response.py ..F.

====================================== FAILURES =======================================
____________________________ TestResponse.test_false_sign _____________________________

self = <test_41_response.TestResponse instance at 0x7f104380bea8>

    def test_false_sign(self):
        xml_response = open(FALSE_ASSERT_SIGNED).read()
        resp = response_factory(
            xml_response, self.conf,
            return_addrs=["http://lingon.catalogix.se:8087/"],
            outstanding_queries={
                "bahigehogffohiphlfmplepdpcohkhhmheppcdie":
                    "http://localhost:8088/sso"},
            timeslack=TIMESLACK, decode=False)
    
        assert isinstance(resp, StatusResponse)
        assert isinstance(resp, AuthnResponse)
        try:
>           resp.verify()

test_41_response.py:109: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
/usr/lib/python2.7/dist-packages/saml2/response.py:964: in verify
    res = self._verify()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <saml2.response.AuthnResponse object at 0x7f104384d350>

    def _verify(self):
        if self.request_id and self.in_response_to and \
                        self.in_response_to != self.request_id:
            logger.error("Not the id I expected: %s != %s" % (
                self.in_response_to, self.request_id))
            return None
    
        try:
            assert self.response.version == "2.0"
        except AssertionError:
            _ver = float(self.response.version)
            if _ver < 2.0:
                raise RequestVersionTooLow()
            else:
                raise RequestVersionTooHigh()
    
        if self.asynchop:
            if self.response.destination and \
                    self.response.destination not in self.return_addrs:
                logger.error("%s not in %s" % (self.response.destination,
                                               self.return_addrs))
                return None
    
>       assert self.issue_instant_ok()
E       AssertionError

/usr/lib/python2.7/dist-packages/saml2/response.py:392: AssertionError
-------------------------------- Captured stderr call ---------------------------------
No handlers could be found for logger "saml2.response"

Any direction would be appreciate. 

Thanks in advance!!

**Comment by jkakavas** [comment]
Hi, 

Why would you want to use v3.0.0 when the latest available is [v4.4.0](https://github.com/rohe/pysaml2/releases/tag/v4.4.0) ?

**Comment by kirotawa** [comment]
I'm running a legacy machine so can't update right now. Would appreciate to know what can fix this test to fail :)

**Comment by jkakavas** [comment]
I don't think there is much value in troubleshooting a failing test case for a very old version. Is this something that fails in normal use and causes a malfunction for your deployment, or is it just the test case that fails and you are wondering why ?

**Comment by kirotawa** [comment]
hm, yeah I can see your point sorry for the noise. It's just a test case that fails and I would like to know why/what is/was the commit that fix it.  Anyway, thanks :)

**Comment by kirotawa** [comment]
ah, I found the commit that fix it: 4e57ac315c , thanks a lot for you help :)
