### ISSUE TITLE
filter_on_attributes raises KeyError on unknown attribute

### ISSUE THREAD

**Issue by tpazderka** [rohe/pysaml2#457]
If the request contains unknown attribute (not registered in any attribute map) the `filter_on_attributes` raises KeyError.

I do believe that the error should be expected and the attribute removed from the request.

**Comment by jkakavas** [comment]
Hi, 

This was caught and raised in #441, and is now fixed in #442 . You can try to install from head or wait a little bit until the new release is tagged.
