### ISSUE TITLE
Metadata validation breaks with non-ascii characters

### ISSUE THREAD

**Issue by rhoerbe** [rohe/pysaml2#463]
The XML infoset at http://mdfeed.test.portalverbund.gv.at/metadata.xml contains German Umlauts in XML elements. pysaml2.sigver breaks because the xml contents is not retrieved correctly (data/digest mismatch)

**Comment by rhoerbe** [comment]
The relevant code (use requests.content instead of requests.text.encode(UTF-8) has already been fixed since 4.4.0. Please release the latest version to pypi.

**Comment by c00kiemon5ter** [comment]
pysaml2 version 4.5.0 has been released. This can now be closed.
