### ISSUE TITLE
Alternatives to loading config metadata when using pysaml2 in web views

### ISSUE THREAD

**Issue by bogdan-ds** [rohe/pysaml2#472]
Hi all,

I've implemented pysaml2 in a web environment and am dealing with a multifederation situation with a lot of metadata, which causes the config object to take quite a while to load. This cannot be exposed in this state as it takes too much time to load. I tried to implement a periodic task to create the object and cache it, but the object itself cannot be pickled. 

Do you have any suggestions on any alternative methods of doing that? Any ideas would be greatly appreciated.

Thanks in advance.

**Comment by livenson** [comment]
Hi,

we had the same issue, ended up patching a bit a solution to load IdP data into database and using it as a cache.

Feel free to check the code (django + drf):

1. Model for caching: https://github.com/opennode/waldur-auth-saml2/blob/develop/src/nodeconductor_saml2/models.py#L6

2. Populating/managing of cache: https://github.com/opennode/waldur-auth-saml2/blob/develop/src/nodeconductor_saml2/utils.py#L21

3. Custom metadata loader: https://github.com/opennode/waldur-auth-saml2/blob/develop/src/nodeconductor_saml2/utils.py#L62

4. Configuration for using that custom loader: https://github.com/opennode/waldur-auth-saml2/blob/develop/src/nodeconductor_saml2/extension.py#L156

5. You can check how it feels like from web perspective at minu.etais.ee (edugain button). Around 20MB of IdP metadata xml behind that button.

**Comment by bogdan-ds** [comment]
Hi @livenson. Thanks a lot for your reply. It's been immensely helpful. I refactored the code into a periodic task and a few other helper functions and works nicely now. Thanks again.

**Comment by bogdan-ds** [comment]
I'm closing this issue as this solution seems to work.
