### ISSUE TITLE
add url to docs to github project details

### ISSUE THREAD

**Issue by wbolster** [rohe/pysaml2#473]
it would be nice if the github project points to

https://pysaml2.readthedocs.io/

to make it more discoverable. it would appear at the top of the github page.

**Comment by wbolster** [comment]
heh, thanks, but i actually referred to the project description and url on github itself, see e.g. https://github.com/wbolster/jsonlines that looks like this:

![image](https://user-images.githubusercontent.com/748944/33069151-dd65c18a-ceb3-11e7-8e0e-512f39dda8a6.png)

**Comment by c00kiemon5ter** [comment]
I thought of that too, but I have no such rights. 
Maybe @rohe can do that.
