### ISSUE TITLE
Current documentation version is still either outdated or release variable is still incorrect

### ISSUE THREAD

**Issue by gene1wood** [rohe/pysaml2#478]
Continuation from Ticket #328 

Currently, the docs have a release variable of [1.2.0beta](https://github.com/rohe/pysaml2/blob/9c04dc7ebbae1791b4234bc0f4f2949f1fe9f3c4/doc/conf.py#L52). Are the docs out of date (and not in sync with the current release of pysaml2 (version `4.5.0`)? Or are the docs up to date and the release variable is wrong?

The impact of this is that when searching for and [viewing the docs](https://pysaml2.readthedocs.org/en/latest/) they show as being for a very different version of the code than the user would be using. This version (`1.2.0beta`) shows up both in the docs and in search results pointing to the docs.

The end result is that when the users searches for docs for pysaml2 `4.5.0`, they only find docs for `1.2.0beta` which is confusing.

The version number in the docs is [1.2.0beta](https://github.com/rohe/pysaml2/blob/9c04dc7ebbae1791b4234bc0f4f2949f1fe9f3c4/doc/conf.py#L52). There haven't been any commits that would change the version number since @rohe [set the version in October 2014](https://github.com/rohe/pysaml2/commit/f05587c9111297ec591755382a71f1ea66cc8015). The intent of this value is to be "[the major project version](http://www.sphinx-doc.org/en/stable/config.html#confval-version)" of the software for which the documentation applies.

So assuming the documentation in the head of master applies to the current [version `4.5.0`](https://github.com/rohe/pysaml2/blob/847e970c5af6a09de61307be3a3d0305eee131f7/src/saml2/__init__.py#L20) of pysaml2, then the "version" and "[release](http://www.sphinx-doc.org/en/stable/config.html#confval-release)" values should be `4.5.0`

Fixes for this are either
* Set the `version` and `release` variables in `conf.py` to the value in [`src/saml/__init__.py`](https://github.com/rohe/pysaml2/blob/847e970c5af6a09de61307be3a3d0305eee131f7/src/saml2/__init__.py#L20)
* Set the `version` and `release` variables in `conf.py` to `''`

**Comment by c00kiemon5ter** [comment]
I made the relevant change and I am now closing this. 
Thanks for the input 👍
