### ISSUE TITLE
Signature error: Signature missing for response

### ISSUE THREAD

**Issue by techbhashya** [rohe/pysaml2#490]
Hello, 

Unable to validate Idp and Sp

I am using the application available under examples idp2 and sp-wsgi to validate idp and sp. I am getting error `Signature error: Signature missing for response`

Replaced base url with my ip and update HOST with my ip. I have generated a new server key based on my hostname updated configuration file `examples/idp2/idp_conf.py` `SERVER_CERT` and `SERVER_KEY`.

Saml server throws 500 Internal server err. Is there any way to fix the issue. 

> _idp.log_:
> ```
> 2018-02-01 01:27:24,593 saml2.idp:ERROR An error occured while creating metadata: 'NoneType' object has no attribute '__getitem__'
> ```

Best Regards,
Radhakrishnan Rk

**Comment by jkakavas** [comment]
Hi, we would probably need a little more information to be able to help out. At minimum, please share your idp_conf.py and sp_conf.py, along with more lines from the logs

**Comment by vivekdhayaal** [comment]
Hi, I face the same issue. please find below the details:

idp_conf.py & sp_conf.py:
===================
I use the default idp_conf.py  and sp_conf.py as-is:
https://github.com/rohe/pysaml2/blob/master/example/idp2/idp_conf.py.example
https://github.com/rohe/pysaml2/blob/master/example/sp-wsgi/sp_conf.py.example
https://github.com/rohe/pysaml2/blob/master/example/sp-wsgi/service_conf.py.example

spx.log:
======
2018-02-11 19:40:08,988 root:INFO Server starting
2018-02-11 19:40:28,115 root:INFO Chosen IdP: 'https://localhost:8088/idp.xml'
2018-02-11 19:40:28,116 saml2.entity:INFO REQUEST: <?xml version='1.0' encoding='UTF-8'?>
<ns0:AuthnRequest xmlns:ns0="urn:oasis:names:tc:SAML:2.0:protocol" xmlns:ns1="urn:oasis:names:tc:SAML:2.0:assertion" xmlns:ns2="http://www.w3.org/2000/09/xmldsig#" AssertionConsumerServiceURL="http://localhost:8087/acs/post" Destination="https://localhost:8088/sso/redirect" ID="id-5Tt6XgkujTLkqxoQ9" IssueInstant="2018-02-11T14:10:28Z" ProtocolBinding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Version="2.0"><ns1:Issuer Format="urn:oasis:names:tc:SAML:2.0:nameid-format:entity">http://localhost:8087/sp.xml</ns1:Issuer><ns2:Signature Id="Signature1"><ns2:SignedInfo><ns2:CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#" /><ns2:SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1" /><ns2:Reference URI="#id-5Tt6XgkujTLkqxoQ9"><ns2:Transforms><ns2:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature" /><ns2:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#" /></ns2:Transforms><ns2:DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1" /><ns2:DigestValue /></ns2:Reference></ns2:SignedInfo><ns2:SignatureValue /><ns2:KeyInfo><ns2:X509Data><ns2:X509Certificate>MIIC8jCCAlugAwIBAgIJAJHg2V5J31I8MA0GCSqGSIb3DQEBBQUAMFoxCzAJBgNVBAYTAlNFMQ0wCwYDVQQHEwRVbWVhMRgwFgYDVQQKEw9VbWVhIFVuaXZlcnNpdHkxEDAOBgNVBAsTB0lUIFVuaXQxEDAOBgNVBAMTB1Rlc3QgU1AwHhcNMDkxMDI2MTMzMTE1WhcNMTAxMDI2MTMzMTE1WjBaMQswCQYDVQQGEwJTRTENMAsGA1UEBxMEVW1lYTEYMBYGA1UEChMPVW1lYSBVbml2ZXJzaXR5MRAwDgYDVQQLEwdJVCBVbml0MRAwDgYDVQQDEwdUZXN0IFNQMIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDkJWP7bwOxtH+E15VTaulNzVQ/0cSbM5G7abqeqSNSs0l0veHr6/ROgW96ZeQ57fzVy2MCFiQRw2fzBs0n7leEmDJyVVtBTavYlhAVXDNa3stgvh43qCfLx+clUlOvtnsoMiiRmo7qf0BoPKTj7c0uLKpDpEbAHQT4OF1HRYVxMwIDAQABo4G/MIG8MB0GA1UdDgQWBBQ7RgbMJFDGRBu9o3tDQDuSoBy7JjCBjAYDVR0jBIGEMIGBgBQ7RgbMJFDGRBu9o3tDQDuSoBy7JqFepFwwWjELMAkGA1UEBhMCU0UxDTALBgNVBAcTBFVtZWExGDAWBgNVBAoTD1VtZWEgVW5pdmVyc2l0eTEQMA4GA1UECxMHSVQgVW5pdDEQMA4GA1UEAxMHVGVzdCBTUIIJAJHg2V5J31I8MAwGA1UdEwQFMAMBAf8wDQYJKoZIhvcNAQEFBQADgYEAMuRwwXRnsiyWzmRikpwinnhTmbooKm5TINPE7A7gSQ710RxioQePPhZOzkM27NnHTrCe2rBVg0EGz7QTd1JIwLPvgoj4VTi/fSha/tXrYUaqc9AqU1kWI4WN+vffBGQ09mo+6CffuFTZYeOhzP/2stAPwCTU4kxEoiy0KpZMANI=</ns2:X509Certificate></ns2:X509Data></ns2:KeyInfo></ns2:Signature><ns0:NameIDPolicy AllowCreate="false" Format="urn:oasis:names:tc:SAML:2.0:nameid-format:persistent" /></ns0:AuthnRequest>
2018-02-11 19:40:28,145 saml2.entity:INFO HTTP REDIRECT
2018-02-11 19:40:43,863 saml2.entity:ERROR Signature Error: Signature missing for response
2018-02-11 19:40:43,863 saml2.client_base:ERROR XML parse error: Signature missing for response


idp.log:
======
2018-02-11 19:39:42,842 saml2:INFO Logging started
2018-02-11 19:40:33,900 saml2.entity:DEBUG receiver addresses: ['https://localhost:8088/sso/redirect']
2018-02-11 19:40:33,901 saml2.entity:DEBUG Binding: urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect
2018-02-11 19:40:33,901 saml2.request:DEBUG xmlstr: <?xml version="1.0" encoding="UTF-8"?>
<ns0:AuthnRequest xmlns:ns0="urn:oasis:names:tc:SAML:2.0:protocol" xmlns:ns1="urn:oasis:names:tc:SAML:2.0:assertion" xmlns:ns2="http://www.w3.org/2000/09/xmldsig#" AssertionConsumerServiceURL="http://localhost:8087/acs/post" Destination="https://localhost:8088/sso/redirect" ID="id-5Tt6XgkujTLkqxoQ9" IssueInstant="2018-02-11T14:10:28Z" ProtocolBinding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Version="2.0"><ns1:Issuer Format="urn:oasis:names:tc:SAML:2.0:nameid-format:entity">http://localhost:8087/sp.xml</ns1:Issuer><ns2:Signature Id="Signature1"><ns2:SignedInfo><ns2:CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/><ns2:SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1"/><ns2:Reference URI="#id-5Tt6XgkujTLkqxoQ9"><ns2:Transforms><ns2:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/><ns2:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/></ns2:Transforms><ns2:DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/><ns2:DigestValue>iSkKUDN2k5oiii1IPpR6XtHaoEk=</ns2:DigestValue></ns2:Reference></ns2:SignedInfo><ns2:SignatureValue>b+F8YbHrQKy0rctaKbMdYsVoafRxHbyInfO4+YdD9du90Q0nGuIEMuaVdZfYhQQI
+NnIdGzSEiaKq7GtyE8nO1v8AW3L+tzajZI83umcVU4kB9TkhbGQgq5vv6u1SLxW
zsmDkXi3sB+s5g8HPYNzQanRBV+lMxJ+vT2e16bsiTc=</ns2:SignatureValue><ns2:KeyInfo><ns2:X509Data><ns2:X509Certificate>MIIC8jCCAlugAwIBAgIJAJHg2V5J31I8MA0GCSqGSIb3DQEBBQUAMFoxCzAJBgNVBAYTAlNFMQ0wCwYDVQQHEwRVbWVhMRgwFgYDVQQKEw9VbWVhIFVuaXZlcnNpdHkxEDAOBgNVBAsTB0lUIFVuaXQxEDAOBgNVBAMTB1Rlc3QgU1AwHhcNMDkxMDI2MTMzMTE1WhcNMTAxMDI2MTMzMTE1WjBaMQswCQYDVQQGEwJTRTENMAsGA1UEBxMEVW1lYTEYMBYGA1UEChMPVW1lYSBVbml2ZXJzaXR5MRAwDgYDVQQLEwdJVCBVbml0MRAwDgYDVQQDEwdUZXN0IFNQMIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDkJWP7bwOxtH+E15VTaulNzVQ/0cSbM5G7abqeqSNSs0l0veHr6/ROgW96ZeQ57fzVy2MCFiQRw2fzBs0n7leEmDJyVVtBTavYlhAVXDNa3stgvh43qCfLx+clUlOvtnsoMiiRmo7qf0BoPKTj7c0uLKpDpEbAHQT4OF1HRYVxMwIDAQABo4G/MIG8MB0GA1UdDgQWBBQ7RgbMJFDGRBu9o3tDQDuSoBy7JjCBjAYDVR0jBIGEMIGBgBQ7RgbMJFDGRBu9o3tDQDuSoBy7JqFepFwwWjELMAkGA1UEBhMCU0UxDTALBgNVBAcTBFVtZWExGDAWBgNVBAoTD1VtZWEgVW5pdmVyc2l0eTEQMA4GA1UECxMHSVQgVW5pdDEQMA4GA1UEAxMHVGVzdCBTUIIJAJHg2V5J31I8MAwGA1UdEwQFMAMBAf8wDQYJKoZIhvcNAQEFBQADgYEAMuRwwXRnsiyWzmRikpwinnhTmbooKm5TINPE7A7gSQ710RxioQePPhZOzkM27NnHTrCe2rBVg0EGz7QTd1JIwLPvgoj4VTi/fSha/tXrYUaqc9AqU1kWI4WN+vffBGQ09mo+6CffuFTZYeOhzP/2stAPwCTU4kxEoiy0KpZMANI=</ns2:X509Certificate></ns2:X509Data></ns2:KeyInfo></ns2:Signature><ns0:NameIDPolicy AllowCreate="false" Format="urn:oasis:names:tc:SAML:2.0:nameid-format:persistent"/></ns0:AuthnRequest>

2018-02-11 19:40:33,905 saml2.sigver:DEBUG ==== Certs from metadata ==== None: [(<open file '<fdopen>', mode 'w+b' at 0x10b16ded0>, '/var/folders/6d/x9nlt5lx0lx2kqtxlld5tm_w0000gn/T/tmpdbyyxH.pem')] ====
2018-02-11 19:40:33,906 saml2.sigver:DEBUG xmlsec command: /usr/local/bin/xmlsec1 --verify --pubkey-cert-pem /var/folders/6d/x9nlt5lx0lx2kqtxlld5tm_w0000gn/T/tmpdbyyxH.pem --id-attr:ID urn:oasis:names:tc:SAML:2.0:protocol:AuthnRequest --store-signatures --node-id id-5Tt6XgkujTLkqxoQ9 --output /var/folders/6d/x9nlt5lx0lx2kqtxlld5tm_w0000gn/T/tmpF8gfEU.xml /var/folders/6d/x9nlt5lx0lx2kqtxlld5tm_w0000gn/T/tmpN9HjHi.xml
2018-02-11 19:40:33,928 saml2.request:INFO request: <?xml version='1.0' encoding='UTF-8'?>
<ns0:AuthnRequest xmlns:ns0="urn:oasis:names:tc:SAML:2.0:protocol" xmlns:ns1="urn:oasis:names:tc:SAML:2.0:assertion" xmlns:ns2="http://www.w3.org/2000/09/xmldsig#" AssertionConsumerServiceURL="http://localhost:8087/acs/post" Destination="https://localhost:8088/sso/redirect" ID="id-5Tt6XgkujTLkqxoQ9" IssueInstant="2018-02-11T14:10:28Z" ProtocolBinding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Version="2.0"><ns1:Issuer Format="urn:oasis:names:tc:SAML:2.0:nameid-format:entity">http://localhost:8087/sp.xml</ns1:Issuer><ns2:Signature Id="Signature1"><ns2:SignedInfo><ns2:CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#" /><ns2:SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1" /><ns2:Reference URI="#id-5Tt6XgkujTLkqxoQ9"><ns2:Transforms><ns2:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature" /><ns2:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#" /></ns2:Transforms><ns2:DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1" /><ns2:DigestValue>iSkKUDN2k5oiii1IPpR6XtHaoEk=</ns2:DigestValue></ns2:Reference></ns2:SignedInfo><ns2:SignatureValue>b+F8YbHrQKy0rctaKbMdYsVoafRxHbyInfO4+YdD9du90Q0nGuIEMuaVdZfYhQQI
+NnIdGzSEiaKq7GtyE8nO1v8AW3L+tzajZI83umcVU4kB9TkhbGQgq5vv6u1SLxW
zsmDkXi3sB+s5g8HPYNzQanRBV+lMxJ+vT2e16bsiTc=</ns2:SignatureValue><ns2:KeyInfo><ns2:X509Data><ns2:X509Certificate>MIIC8jCCAlugAwIBAgIJAJHg2V5J31I8MA0GCSqGSIb3DQEBBQUAMFoxCzAJBgNVBAYTAlNFMQ0wCwYDVQQHEwRVbWVhMRgwFgYDVQQKEw9VbWVhIFVuaXZlcnNpdHkxEDAOBgNVBAsTB0lUIFVuaXQxEDAOBgNVBAMTB1Rlc3QgU1AwHhcNMDkxMDI2MTMzMTE1WhcNMTAxMDI2MTMzMTE1WjBaMQswCQYDVQQGEwJTRTENMAsGA1UEBxMEVW1lYTEYMBYGA1UEChMPVW1lYSBVbml2ZXJzaXR5MRAwDgYDVQQLEwdJVCBVbml0MRAwDgYDVQQDEwdUZXN0IFNQMIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDkJWP7bwOxtH+E15VTaulNzVQ/0cSbM5G7abqeqSNSs0l0veHr6/ROgW96ZeQ57fzVy2MCFiQRw2fzBs0n7leEmDJyVVtBTavYlhAVXDNa3stgvh43qCfLx+clUlOvtnsoMiiRmo7qf0BoPKTj7c0uLKpDpEbAHQT4OF1HRYVxMwIDAQABo4G/MIG8MB0GA1UdDgQWBBQ7RgbMJFDGRBu9o3tDQDuSoBy7JjCBjAYDVR0jBIGEMIGBgBQ7RgbMJFDGRBu9o3tDQDuSoBy7JqFepFwwWjELMAkGA1UEBhMCU0UxDTALBgNVBAcTBFVtZWExGDAWBgNVBAoTD1VtZWEgVW5pdmVyc2l0eTEQMA4GA1UECxMHSVQgVW5pdDEQMA4GA1UEAxMHVGVzdCBTUIIJAJHg2V5J31I8MAwGA1UdEwQFMAMBAf8wDQYJKoZIhvcNAQEFBQADgYEAMuRwwXRnsiyWzmRikpwinnhTmbooKm5TINPE7A7gSQ710RxioQePPhZOzkM27NnHTrCe2rBVg0EGz7QTd1JIwLPvgoj4VTi/fSha/tXrYUaqc9AqU1kWI4WN+vffBGQ09mo+6CffuFTZYeOhzP/2stAPwCTU4kxEoiy0KpZMANI=</ns2:X509Certificate></ns2:X509Data></ns2:KeyInfo></ns2:Signature><ns0:NameIDPolicy AllowCreate="false" Format="urn:oasis:names:tc:SAML:2.0:nameid-format:persistent" /></ns0:AuthnRequest>
2018-02-11 19:40:33,932 saml2.entity:DEBUG Loaded request
2018-02-11 19:40:33,932 saml2.entity:DEBUG Verified request
2018-02-11 19:40:34,252 saml2.idp:ERROR An error occured while creating metadata: 'NoneType' object has no attribute '__getitem__'
2018-02-11 19:40:43,816 saml2.mdstore:DEBUG service(http://localhost:8087/sp.xml, spsso_descriptor, assertion_consumer_service, urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST)
2018-02-11 19:40:43,816 saml2.mdstore:DEBUG service => [{'index': '1', 'binding': 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST', '__class__': 'urn:oasis:names:tc:SAML:2.0:metadata&AssertionConsumerService', 'location': 'http://localhost:8087/acs/post'}]
2018-02-11 19:40:43,816 saml2.mdstore:DEBUG service(http://localhost:8087/sp.xml, spsso_descriptor, assertion_consumer_service, urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST)
2018-02-11 19:40:43,816 saml2.mdstore:DEBUG service => [{'index': '1', 'binding': 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST', '__class__': 'urn:oasis:names:tc:SAML:2.0:metadata&AssertionConsumerService', 'location': 'http://localhost:8087/acs/post'}]
2018-02-11 19:40:43,816 saml2.ident:DEBUG failed to find userid roland in IdentDB
2018-02-11 19:40:43,816 saml2.ident:DEBUG local_policy: <saml2.assertion.Policy object at 0x10b193790>, name_id_policy: <?xml version='1.0' encoding='UTF-8'?>
<ns0:NameIDPolicy xmlns:ns0="urn:oasis:names:tc:SAML:2.0:protocol" AllowCreate="false" Format="urn:oasis:names:tc:SAML:2.0:nameid-format:persistent" />
2018-02-11 19:40:43,817 saml2.server:DEBUG construct_nameid: roland => <?xml version='1.0' encoding='UTF-8'?>
<ns0:NameID xmlns:ns0="urn:oasis:names:tc:SAML:2.0:assertion" Format="urn:oasis:names:tc:SAML:2.0:nameid-format:persistent" NameQualifier="https://localhost:8088/idp.xml" SPNameQualifier="http://localhost:8087/sp.xml">4689d11ac3db7ff6debde0bb6dc4dfe82686ffadd50e33e49cccb283bc51f87a</ns0:NameID>
2018-02-11 19:40:43,819 saml2.entity:INFO HTTP POST

**Comment by c00kiemon5ter** [comment]
Not requesting a signature was the default behaviour prior to v4.5.0 – more details on #424, #439 and #470. The fix for this is to not request a signature by setting the `want_response_signed` option to `False`.
